# Linter config file for golangci-lint
# Example - https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  skip-dirs: []

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: false
  fast: false
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck
#    - gofmt
    - gosimple
    - goconst
    - misspell
    - unconvert
    - varcheck
    - unused
    - deadcode
    - unparam
    - ineffassign
#    - gochecknoglobals
  disable:

  
